### ISSUE TITLE
Compiling fails in Ubuntu 16.04

### ISSUE THREAD

**Issue by Cordoha** [adbrant/ArableInstruments#4]
Here are some errors I get trying to build in the latest build of Rack using Ubuntu 16.04.

src/AudibleInstruments.cpp: In function ‘void init(rack::Plugin*)’:
src/AudibleInstruments.cpp:16:10: error: ‘struct rack::Plugin’ has no member named ‘name’
  plugin->name = "Arable Instruments";
          ^
src/AudibleInstruments.cpp:17:10: error: ‘struct rack::Plugin’ has no member named ‘homepageUrl’
  plugin->homepageUrl = "https://github.com/adbrant/ArableInstruments";
          ^
src/AudibleInstruments.cpp:19:72: error: no matching function for call to ‘createModel(rack::Plugin*&, const char [5], const char [27])’
  createModel<CloudsWidget>(plugin, "Joni", "Joni - Texture Synthesizer");
                                                                        ^
In file included from src/AudibleInstruments.hpp:1:0,
                 from src/AudibleInstruments.cpp:1:
../../include/rack.hpp:22:8: note: candidate: template<class TModuleWidget, class ... Tags> rack::Model* rack::createModel(std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, Tags ...)
 Model *createModel(std::string manufacturer, std::string slug, std::string n
        ^
../../include/rack.hpp:22:8: note:   template argument deduction/substitution failed:
src/AudibleInstruments.cpp:19:72: note:   cannot convert ‘plugin’ (type ‘rack::Plugin*’) to type ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’
  createModel<CloudsWidget>(plugin, "Joni", "Joni - Texture Synthesizer");
                                                                        ^
../../compile.mk:53: recipe for target 'build/src/AudibleInstruments.cpp.o' failed
make: *** [build/src/AudibleInstruments.cpp.o] Error 1

**Comment by adbrant** [comment]
I think this is due to the plugins being compatible with v0.4.0 instead of v0.50 at the time.
I've updated the plugins to work with v0.5.0 now so it may work now.
